version: "2"

formatters:
  enable:
    - gofmt
    - goimports

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocyclo
    - gocritic
    - gosec
    - misspell
    - unconvert
    - unparam
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
    gocyclo:
      min-complexity: 15
    gocritic:
      enabled-tags:
        - performance
        - style
        - experimental
      disabled-checks:
        - whyNoLint
    gosec:
      excludes:
        - G204
        - G304
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - (*os.File).Close
        - (*bufio.Writer).Flush
  exclusions:
    presets:
      - comments
      - std-error-handling
    rules:
      - path: _test\.go
        linters:
          - gosec
      - path: "pkg/types/mocks.go"
        linters:
          - gocritic
          - gosec
          - errcheck

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

output:
  formats:
    colored-line-number: {}
  print-issued-lines: true
  print-linter-name: true
